"""update penerima manfaat column dokumen

Revision ID: 2fc38f9638c2
Revises: fe5bf52c0842
Create Date: 2024-06-30 23:16:18.787747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fc38f9638c2'
down_revision = 'fe5bf52c0842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_manfaat', schema=None) as batch_op:
        batch_op.alter_column('dokumen',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_manfaat', schema=None) as batch_op:
        batch_op.alter_column('dokumen',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
