"""update profile

Revision ID: 3920f0ce9efb
Revises: 6077bde5ed0b
Create Date: 2024-06-30 16:47:00.931558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3920f0ce9efb'
down_revision = '6077bde5ed0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('dokumen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dokumen', mysql.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
