"""empty message

Revision ID: 6077bde5ed0b
Revises: 
Create Date: 2024-06-30 14:37:28.693067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6077bde5ed0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_manfaat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_manfaat', schema=None) as batch_op:
        batch_op.drop_column('keterangan')

    # ### end Alembic commands ###
