"""update penerima manfaat

Revision ID: 80421f6350f6
Revises: 3920f0ce9efb
Create Date: 2024-06-30 16:48:28.060853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80421f6350f6'
down_revision = '3920f0ce9efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_manfaat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dokumen', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_manfaat', schema=None) as batch_op:
        batch_op.drop_column('dokumen')

    # ### end Alembic commands ###
