"""initial migrate

Revision ID: 842231b111a1
Revises: 
Create Date: 2024-05-31 13:35:44.637918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842231b111a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_bantuan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_bantuan', sa.String(length=250), nullable=False),
    sa.Column('anggaran_per_paket', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('aktif', 'nonaktif'), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('nama', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user'), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_nik'), ['nik'], unique=True)

    op.create_table('penerima_manfaat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('jenisBantuanId', sa.BigInteger(), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=250), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('telepon', sa.String(length=15), nullable=False),
    sa.Column('provinsi', sa.String(length=250), nullable=False),
    sa.Column('pekerjaan', sa.String(length=250), nullable=False),
    sa.Column('penghasilan', sa.Float(), nullable=False),
    sa.Column('rekening', sa.String(length=50), nullable=False),
    sa.Column('dokumen', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Enum('aktif', 'nonaktif', 'ditolak', 'belum diverifikasi'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jenisBantuanId'], ['jenis_bantuan.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_penyaluran',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('penerimaManfaatId', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('proses', 'selesai'), nullable=False),
    sa.Column('jadwal_penyaluran', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['penerimaManfaatId'], ['penerima_manfaat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jadwal_penyaluran')
    op.drop_table('penerima_manfaat')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nik'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('jenis_bantuan')
    # ### end Alembic commands ###
